CREATE DATABASE IF NOT EXISTS pptdb DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE pptdb;

CREATE TABLE IF NOT EXISTS ppt_files (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  path VARCHAR(1024) NOT NULL,
  upload_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
